//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int NHS_Number { get; set; }
        public string Appointment1 { get; set; }
        public string Consultant { get; set; }
    }
}
