//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public string userName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string DoB { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public int NHS_Number { get; set; }
    }
}
